#if os(macOS)
import Foundation

/// Sandbox support for `AgentSetupEngine` (`sandbox-cli.sh`). This only ever
/// *writes* a sandbox-exec `.sb` profile and a wrapper script under
/// `~/.sandbox/<cmd>` — it never launches `sandbox-exec` or any other process.
extension AgentSetupEngine {
    static func sandboxStatus(
        _ target: AgentSetupTarget,
        prefix: URL,
        home: URL = FileManager.default.homeDirectoryForCurrentUser
    ) -> AgentSandboxStatus {
        let fileManager = FileManager.default
        let paths = paths(for: target, prefix: prefix, home: home)
        let profileExists = fileManager.fileExists(atPath: paths.sandboxProfile.path)
        var rules: [String] = []
        if profileExists, let contents = try? String(contentsOf: paths.sandboxProfile, encoding: .utf8) {
            rules = contents
                .split(separator: "\n")
                .map { $0.trimmingCharacters(in: .whitespaces) }
                .filter { $0.hasPrefix("(allow") || $0.hasPrefix("(deny") }
        }
        return AgentSandboxStatus(
            profileExists: profileExists,
            profilePath: paths.sandboxProfile.path,
            wrapperReady: fileManager.isExecutableFile(atPath: paths.sandboxWrapper.path),
            linked: exists(paths.sandboxBinLink),
            binPath: paths.sandboxBinLink.path,
            rules: rules
        )
    }

    static func sandboxInstall(
        _ target: AgentSetupTarget,
        prefix: URL,
        home: URL = FileManager.default.homeDirectoryForCurrentUser
    ) throws {
        let fileManager = FileManager.default
        let paths = paths(for: target, prefix: prefix, home: home)
        do {
            try fileManager.createDirectory(at: paths.sandboxDir, withIntermediateDirectories: true)
            try fileManager.createDirectory(at: paths.binDir, withIntermediateDirectories: true)

            try replaceItem(at: paths.sandboxProfile, with: sandboxProfile(target: target, paths: paths, home: home))

            let wrapperScript = """
            #!/usr/bin/env bash
            # Sandboxed wrapper for \(target.command) — \(target.command)
            # Profile: \(paths.sandboxProfile.path)
            exec sandbox-exec -f "\(paths.sandboxProfile.path)" "\(paths.wrapper.path)" "$@"

            """
            try replaceItem(at: paths.sandboxWrapper, with: wrapperScript)
            try fileManager.setAttributes([.posixPermissions: 0o755], ofItemAtPath: paths.sandboxWrapper.path)

            removeIfPresent(paths.sandboxBinLink)
            try fileManager.createSymbolicLink(at: paths.sandboxBinLink, withDestinationURL: paths.sandboxWrapper)
        } catch {
            throw AgentSetupError.filesystem(error.localizedDescription)
        }
    }

    static func sandboxUninstall(
        _ target: AgentSetupTarget,
        prefix: URL,
        home: URL = FileManager.default.homeDirectoryForCurrentUser
    ) throws {
        let fileManager = FileManager.default
        let paths = paths(for: target, prefix: prefix, home: home)
        do {
            if fileManager.fileExists(atPath: paths.sandboxDir.path) { try fileManager.removeItem(at: paths.sandboxDir) }
            removeIfPresent(paths.sandboxBinLink)
        } catch {
            throw AgentSetupError.filesystem(error.localizedDescription)
        }
    }

    private static func sandboxProfile(target: AgentSetupTarget, paths: Paths, home: URL) -> String {
        let cacheDir = home.appendingPathComponent(".cache", isDirectory: true).path
        return """
        ;; sandbox profile for \(target.command) — \(target.displayName) CLI
        ;; Generated by Cupertino's Agent CLI Setup page

        (version 1)
        (deny default)
        (allow sysctl-read)
        (allow process-fork)
        (allow process-exec)
        (allow signal)
        (allow file-read* (path "/usr/lib") (path "/usr/share") (path "/System/Library") (path "/Library/Apple") (path "/private/var/run"))
        (allow file-read* (path "\(paths.configDir.path)") (path "\(paths.dataDir.path)"))
        (allow file-write* (path "\(paths.configDir.path)") (path "\(paths.dataDir.path)"))
        (allow file-read* (path "/tmp") (path "\(cacheDir)"))
        (allow file-write* (path "/tmp") (path "\(cacheDir)"))
        (allow file-read* (path "\(paths.wrapper.path)"))
        (allow network* (local ip "localhost:*") (remote tcp))
        (allow file-read* (path "/usr/local") (path "/opt/homebrew"))

        """
    }
}
#endif
